from __future__ import annotations

import json
from typing import Any

import psycopg
from psycopg.rows import dict_row

from models import AiUsageMetrics, CandidateProfileExtraction, JobProfileExtraction


class PostgresStore:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url

    async def ensure_schema(self) -> None:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            async with connection.cursor() as cursor:
                await cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS settings (
                        key TEXT PRIMARY KEY,
                        value TEXT NOT NULL,
                        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                    );
                    CREATE TABLE IF NOT EXISTS ai_logs (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT,
                        feature TEXT NOT NULL,
                        model TEXT,
                        model_version TEXT,
                        prompt_hash TEXT,
                        prompt TEXT,
                        response TEXT,
                        parsed_result TEXT,
                        skills TEXT,
                        duration_ms BIGINT,
                        input_tokens BIGINT,
                        output_tokens BIGINT,
                        success BIGINT DEFAULT 1,
                        error_message TEXT,
                        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                    );
                    CREATE TABLE IF NOT EXISTS jobs (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        graph_job_id TEXT,
                        title TEXT NOT NULL,
                        company TEXT,
                        recruiter_company TEXT,
                        employer_company TEXT,
                        description TEXT,
                        requirements TEXT,
                        about_us TEXT,
                        benefits TEXT,
                        location TEXT,
                        type TEXT DEFAULT 'Vollzeit',
                        status TEXT DEFAULT 'Offen',
                        url TEXT,
                        raw_text TEXT,
                        parsed_profile_json TEXT,
                        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                    );
                    CREATE TABLE IF NOT EXISTS candidate_texts (
                        candidate_id TEXT PRIMARY KEY,
                        candidate_name TEXT,
                        source TEXT,
                        original_text TEXT NOT NULL,
                        anonymized_text TEXT,
                        anonymization_map TEXT,
                        profile_json TEXT,
                        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )
                for table in ("ai_logs", "jobs"):
                    await cursor.execute(f"CREATE SEQUENCE IF NOT EXISTS {table}_id_seq")
                    await cursor.execute(f"ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval('{table}_id_seq')")
                    await cursor.execute(f"ALTER SEQUENCE {table}_id_seq OWNED BY {table}.id")
                    await cursor.execute(
                        f"SELECT setval('{table}_id_seq', COALESCE((SELECT MAX(id) FROM {table}), 0) + 1, false)"
                    )
                await cursor.execute("ALTER TABLE candidates ADD COLUMN IF NOT EXISTS parsing_method TEXT")

    async def read_ai_usage(self) -> AiUsageMetrics:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            async with connection.cursor() as cursor:
                await cursor.execute(
                    """
                    SELECT COUNT(*),
                           COALESCE(SUM(COALESCE(input_tokens, 0)), 0),
                           COALESCE(SUM(COALESCE(output_tokens, 0)), 0)
                    FROM ai_logs
                    """
                )
                row = await cursor.fetchone()
        if not row:
            return AiUsageMetrics()
        input_tokens = int(row[1] or 0)
        output_tokens = int(row[2] or 0)
        return AiUsageMetrics(
            calls=int(row[0] or 0),
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=input_tokens + output_tokens,
        )

    async def write_ai_log(self, values: tuple[Any, ...]) -> None:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            await connection.execute(
                """
                INSERT INTO ai_logs (
                    user_id, feature, model, model_version, prompt_hash, prompt, response, parsed_result,
                    skills, duration_ms, input_tokens, output_tokens, success, error_message
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                """,
                values,
            )

    async def store_candidate_text(
        self,
        candidate_id: str,
        raw_text: str,
        *,
        candidate_name: str | None = None,
        source: str | None = None,
        profile_json: dict[str, Any] | None = None,
    ) -> None:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            await connection.execute(
                """
                INSERT INTO candidate_texts (
                    candidate_id, candidate_name, source, original_text, anonymized_text,
                    anonymization_map, profile_json
                ) VALUES (%s, %s, %s, %s, NULL, NULL, %s)
                ON CONFLICT (candidate_id) DO UPDATE SET
                    candidate_name = EXCLUDED.candidate_name,
                    source = COALESCE(EXCLUDED.source, candidate_texts.source),
                    original_text = EXCLUDED.original_text,
                    anonymized_text = NULL,
                    anonymization_map = NULL,
                    profile_json = EXCLUDED.profile_json,
                    updated_at = CURRENT_TIMESTAMP
                """,
                (
                    candidate_id,
                    candidate_name,
                    source,
                    raw_text,
                    json.dumps(profile_json, ensure_ascii=False) if profile_json is not None else None,
                ),
            )

    async def get_candidate_text(self, candidate_id: str) -> dict[str, Any] | None:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            async with connection.cursor(row_factory=dict_row) as cursor:
                await cursor.execute(
                    """
                    SELECT candidate_id, candidate_name, source, original_text, anonymized_text,
                           anonymization_map, profile_json
                    FROM candidate_texts
                    WHERE candidate_id = %s
                    """,
                    (candidate_id,),
                )
                row = await cursor.fetchone()
        if row is None:
            return None
        mapping = row.get("anonymization_map")
        profile_json = row.get("profile_json")
        return {
            **row,
            "mapping": json.loads(mapping) if isinstance(mapping, str) and mapping.strip() else {},
            "profile_json": json.loads(profile_json) if isinstance(profile_json, str) and profile_json.strip() else None,
        }

    async def store_candidate_anonymization(
        self,
        candidate_id: str,
        anonymized_text: str,
        mapping: dict[str, str],
    ) -> None:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            await connection.execute(
                """
                UPDATE candidate_texts
                SET anonymized_text = %s,
                    anonymization_map = %s,
                    updated_at = CURRENT_TIMESTAMP
                WHERE candidate_id = %s
                """,
                (anonymized_text, json.dumps(mapping, ensure_ascii=False), candidate_id),
            )

    async def list_candidates_for_backfill(self) -> list[dict[str, Any]]:
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            async with connection.cursor(row_factory=dict_row) as cursor:
                await cursor.execute(
                    """
                    SELECT
                        c.id::text AS candidate_id,
                        c.name,
                        c.email,
                        c.phone,
                        c.location,
                        c.experience,
                        c.skills,
                        c.education,
                        c.desired_salary,
                        c.availability,
                        c.languages,
                        c.certificates,
                        c.drivers_license,
                        c.mobility,
                        c.notes,
                        c.tags,
                        c.source,
                        c.linkedin_url,
                        c.xing_url,
                        c.github_url,
                        c.portfolio_url,
                        c.notice_period,
                        c.nationality,
                        c.current_employer,
                        c.current_position,
                        c.gender,
                        c.parsing_method,
                        COALESCE((
                            SELECT json_agg(
                                json_build_object(
                                    'employer', h.employer,
                                    'position', h.position,
                                    'from_date', h.from_date,
                                    'to_date', h.to_date,
                                    'is_current', h.is_current,
                                    'description', h.description,
                                    'location', h.location
                                )
                                ORDER BY h.id
                            )
                            FROM candidate_work_history h
                            WHERE h.candidate_id = c.id
                        ), '[]'::json) AS work_history,
                        COALESCE((
                            SELECT json_agg(
                                json_build_object(
                                    'institution', e.institution,
                                    'degree', e.degree,
                                    'field_of_study', e.field_of_study,
                                    'from_date', e.from_date,
                                    'to_date', e.to_date,
                                    'description', e.description
                                )
                                ORDER BY e.id
                            )
                            FROM candidate_education e
                            WHERE e.candidate_id = c.id
                        ), '[]'::json) AS education_history
                    FROM candidates c
                    ORDER BY c.id
                    """
                )
                rows = await cursor.fetchall()
        return [dict(row) for row in rows]

    async def insert_candidate(self, profile: CandidateProfileExtraction, source: str | None = None) -> int:
        skills = ", ".join(item.name for item in profile.skills) or None
        languages = ", ".join(
            f"{item.name} ({item.level})" if item.level else item.name
            for item in profile.languages
        ) or None
        education = ", ".join(
            f"{item.level} {item.field_of_study}" for item in profile.educations
        ) or profile.education

        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            async with connection.cursor(row_factory=dict_row) as cursor:
                await cursor.execute(
                    """
                    INSERT INTO candidates (
                        name, email, phone, location, experience, skills, education,
                        desired_salary, availability, languages, certificates,
                        drivers_license, mobility, notes, status, tags, source, linkedin_url,
                        xing_url, github_url, portfolio_url, notice_period, nationality,
                        current_employer, current_position, gender, parsing_method
                    ) VALUES (
                        %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
                        %s, 'Aktiv', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                    ) RETURNING id
                    """,
                    (
                        profile.name,
                        profile.email,
                        profile.phone,
                        profile.location,
                        profile.experience,
                        skills,
                        education,
                        profile.desired_salary,
                        profile.availability,
                        languages,
                        profile.certificates,
                        profile.drivers_license,
                        profile.mobility,
                        profile.notes,
                        profile.tags,
                        source,
                        profile.linkedin_url,
                        profile.xing_url,
                        profile.github_url,
                        profile.portfolio_url,
                        profile.notice_period,
                        profile.nationality,
                        profile.current_employer,
                        profile.current_position,
                        profile.gender,
                        profile.parsing_method,
                    ),
                )
                row = await cursor.fetchone()
                if row is None:
                    raise RuntimeError("PostgreSQL did not return a candidate id")
                candidate_id = int(row["id"])

                for item in profile.work_history:
                    if not item.employer or not item.position:
                        continue
                    await cursor.execute(
                        """
                        INSERT INTO candidate_work_history (
                            candidate_id, employer, position, from_date, to_date,
                            is_current, description, location
                        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        (
                            candidate_id, item.employer, item.position, item.from_date,
                            item.to_date, 1 if item.is_current else 0, item.description, item.location,
                        ),
                    )

                for item in profile.education_history:
                    if not item.institution:
                        continue
                    await cursor.execute(
                        """
                        INSERT INTO candidate_education (
                            candidate_id, institution, degree, field_of_study,
                            from_date, to_date, description
                        ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                        """,
                        (
                            candidate_id, item.institution, item.degree, item.field_of_study,
                            item.from_date, item.to_date, item.description,
                        ),
                    )
        return candidate_id

    async def upsert_job(self, job_id: str, raw_text: str, profile: JobProfileExtraction) -> int:
        description = raw_text.strip() if raw_text and raw_text.strip() else self._render_plain_text(profile)
        requirements = self._summarize_requirements(profile)
        async with await psycopg.AsyncConnection.connect(self.database_url) as connection:
            async with connection.cursor(row_factory=dict_row) as cursor:
                await cursor.execute(
                    """
                    INSERT INTO jobs (
                        graph_job_id, title, company, recruiter_company, employer_company, description,
                        requirements, about_us, benefits, location, type, status, url, raw_text,
                        parsed_profile_json
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, NULL, NULL, %s, %s, 'Offen', NULL, %s, %s)
                    RETURNING id
                    """,
                    (
                        job_id,
                        profile.title,
                        profile.company,
                        profile.recruiter_company,
                        profile.employer_company,
                        description,
                        requirements,
                        profile.location,
                        profile.employment_type or "Vollzeit",
                        raw_text,
                        json.dumps(profile.model_dump(), ensure_ascii=False),
                    ),
                )
                row = await cursor.fetchone()
        if row is None:
            raise RuntimeError("PostgreSQL did not return a job id")
        return int(row["id"])

    @staticmethod
    def _summarize_requirements(profile: JobProfileExtraction) -> str | None:
        parts: list[str] = []
        mandatory = [item.name for item in profile.required_skills if item.priority == "Mandatory"]
        optional = [item.name for item in profile.required_skills if item.priority == "NiceToHave"]
        if mandatory:
            parts.append(f"Mandatory skills: {', '.join(mandatory)}")
        if optional:
            parts.append(f"Nice-to-have skills: {', '.join(optional)}")
        if profile.required_languages:
            parts.append("Languages: " + ", ".join(item.name for item in profile.required_languages))
        if profile.required_degrees:
            parts.append(
                "Degrees: " + ", ".join(f"{item.level} {item.field_of_study}" for item in profile.required_degrees)
            )
        if profile.industries:
            parts.append("Industries: " + ", ".join(item.name for item in profile.industries))
        return " | ".join(parts) if parts else None

    @staticmethod
    def _render_plain_text(profile: JobProfileExtraction) -> str:
        parts = [profile.title]
        if profile.company:
            parts.append(f"Company: {profile.company}")
        if profile.location:
            parts.append(f"Location: {profile.location}")
        if profile.employment_type:
            parts.append(f"Employment type: {profile.employment_type}")
        return "\n".join(parts)
