const fs = require('fs');
const deasync = require('deasync');
const { Client, types } = require('pg');


types.setTypeParser(20, value => Number(value));
types.setTypeParser(1700, value => Number(value));

function waitFor(register) {
  let complete = false;
  let error;
  let value;
  register((err, result) => {
    error = err;
    value = result;
    complete = true;
  });
  deasync.loopWhile(() => !complete);
  if (error) throw error;
  return value;
}

function replacePlaceholders(sql) {
  let index = 0;
  let quote = null;
  let output = '';
  for (let position = 0; position < sql.length; position += 1) {
    const char = sql[position];
    if (quote) {
      output += char;
      if (char === quote && sql[position + 1] === quote) {
        output += sql[position + 1];
        position += 1;
      } else if (char === quote) {
        quote = null;
      }
      continue;
    }
    if (char === "'" || char === '"') {
      quote = char;
      output += char;
    } else if (char === '?') {
      index += 1;
      output += `$${index}`;
    } else {
      output += char;
    }
  }
  return output;
}

function translateDateFunctions(sql) {
  return sql
    .replace(/datetime\(\?,\s*'start of day'\)/gi, "date_trunc('day', ?::timestamp)")
    .replace(/datetime\(\?,\s*'\+1 day',\s*'start of day'\)/gi, "date_trunc('day', ?::timestamp) + INTERVAL '1 day'")
    .replace(/datetime\('now',\s*'start of day'\)/gi, "date_trunc('day', CURRENT_TIMESTAMP)")
    .replace(/datetime\('now',\s*'start of month',\s*'-1 month'\)/gi, "date_trunc('month', CURRENT_TIMESTAMP) - INTERVAL '1 month'")
    .replace(/datetime\('now',\s*'start of month'\)/gi, "date_trunc('month', CURRENT_TIMESTAMP)")
    .replace(/datetime\('now',\s*'-'\s*\|\|\s*\?\s*\|\|\s*' days'\)/gi, "CURRENT_TIMESTAMP - (? * INTERVAL '1 day')")
    .replace(/datetime\('now',\s*'([+-]?\d+) days?'\)/gi, (_, amount) => `(CURRENT_TIMESTAMP + INTERVAL '${amount} days')`)
    .replace(/datetime\('now',\s*'([+-]?\d+) hours?'\)/gi, (_, amount) => `(CURRENT_TIMESTAMP + INTERVAL '${amount} hours')`)
    .replace(/datetime\('now',\s*'([+-]?\d+) months?'\)/gi, (_, amount) => `(CURRENT_TIMESTAMP + INTERVAL '${amount} months')`)
    .replace(/datetime\((COALESCE\([^)]+\)),\s*'\+'\s*\|\|\s*\?\s*\|\|\s*' months'\)/gi, "$1 + (? * INTERVAL '1 month')")
    .replace(/datetime\('now'\)/gi, 'CURRENT_TIMESTAMP')
    .replace(/date\('now',\s*'([+-]?\d+) days?'\)/gi, (_, amount) => `(CURRENT_DATE + INTERVAL '${amount} days')`)
    .replace(/date\('now'\)/gi, 'CURRENT_DATE')
    .replace(/strftime\('%Y-%m',\s*([^)]+)\)/gi, "to_char($1, 'YYYY-MM')")
    .replace(/julianday\('now'\)/gi, 'EXTRACT(EPOCH FROM CURRENT_TIMESTAMP) / 86400.0')
    .replace(/julianday\(([^)]+)\)/gi, 'EXTRACT(EPOCH FROM $1::timestamp) / 86400.0');
}

function translateInsertMode(sql) {
  const returningMatch = sql.match(/\s+(RETURNING\s+[a-z_][a-z0-9_]*)\s*;?\s*$/i);
  const returningClause = returningMatch ? ` ${returningMatch[1]}` : '';
  const statement = returningMatch ? sql.slice(0, returningMatch.index) : sql;
  const ignored = /^\s*INSERT\s+OR\s+IGNORE\s+INTO\s+(settings|user_job_access)\b/i.exec(statement);
  if (ignored) {
    const target = ignored[1].toLowerCase() === 'settings' ? 'key' : 'user_id, job_id';
    return statement.replace(/INSERT\s+OR\s+IGNORE\s+INTO/i, 'INSERT INTO').replace(/;?\s*$/, ` ON CONFLICT (${target}) DO NOTHING${returningClause}`);
  }

  if (/^\s*INSERT\s+OR\s+REPLACE\s+INTO\s+settings\b/i.test(statement)) {
    return statement
      .replace(/INSERT\s+OR\s+REPLACE\s+INTO/i, 'INSERT INTO')
      .replace(/;?\s*$/, ` ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = EXCLUDED.updated_at${returningClause}`);
  }
  return sql;
}

function translateSql(sql) {
  let translated = translateDateFunctions(String(sql));
  translated = translated
    .replace(/INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bAUTOINCREMENT\b/gi, '')
    .replace(/\bDATETIME\b/gi, 'TIMESTAMPTZ')
    .replace(/\bREAL\b/gi, 'DOUBLE PRECISION')
    .replace(/\bINTEGER\b/gi, 'BIGINT');
  translated = translateInsertMode(translated);
  return replacePlaceholders(translated);
}

class PostgresStatement {
  constructor(database, sql) {
    this.database = database;
    this.sql = sql;
  }

  all(...params) {
    return this.database.query(this.sql, params).rows;
  }

  get(...params) {
    return this.database.query(this.sql, params).rows[0];
  }

  run(...params) {
    let sql = this.sql;
    const insertMatch = /^\s*INSERT(?:\s+OR\s+(?:IGNORE|REPLACE))?\s+INTO\s+([a-z_][a-z0-9_]*)/i.exec(sql);
    if (insertMatch && insertMatch[1].toLowerCase() !== 'settings' && !/\bRETURNING\b/i.test(sql)) {
      sql = `${sql.replace(/;?\s*$/, '')} RETURNING id`;
    }
    const result = this.database.query(sql, params);
    return {
      changes: result.rowCount || 0,
      lastInsertRowid: result.rows[0]?.id,
    };
  }
}

class PostgresDatabase {
  constructor(connectionString = process.env.DATABASE_URL) {
    if (!connectionString) throw new Error('DATABASE_URL muss für PostgreSQL gesetzt sein');
    this.connectionString = connectionString;
    this.client = new Client({ connectionString });
    waitFor(done => this.client.connect(done));
  }

  query(sql, params = []) {
    const values = params.map(value => value === undefined ? null : value);
    const translatedSql = translateSql(sql);
    try {
      return waitFor(done => this.client.query(translatedSql, values, done));
    } catch (error) {
      error.translatedSql = translatedSql;
      throw error;
    }
  }

  prepare(sql) {
    return new PostgresStatement(this, sql);
  }

  exec(sql) {
    this.query(sql);
    return this;
  }

  pragma() {
    return undefined;
  }

  transaction(callback) {
    return (...args) => {
      this.query('BEGIN');
      try {
        const result = callback(...args);
        this.query('COMMIT');
        return result;
      } catch (error) {
        this.query('ROLLBACK');
        throw error;
      }
    };
  }

  backup(targetPath) {
    return new Promise((resolve, reject) => {
      try {
        const tables = this.query(
          "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name"
        ).rows;
        const dump = {
          format: 'hrtool-postgresql-json-v1',
          createdAt: new Date().toISOString(),
          tables: {},
        };
        for (const { table_name: tableName } of tables) {
          if (!/^[a-z_][a-z0-9_]*$/i.test(tableName)) continue;
          dump.tables[tableName] = this.query(`SELECT * FROM ${tableName}`).rows;
        }
        fs.writeFileSync(targetPath, JSON.stringify(dump, null, 2));
        resolve();
      } catch (error) {
        reject(error);
      }
    });
  }

  ensureIdentityDefaults() {
    const rows = this.query(
      "SELECT table_name FROM information_schema.columns WHERE table_schema = 'public' AND column_name = 'id' AND data_type IN ('bigint', 'integer')"
    ).rows;
    for (const { table_name: tableName } of rows) {
      if (!/^[a-z_][a-z0-9_]*$/i.test(tableName)) continue;
      const sequenceName = `${tableName}_id_seq`;
      this.query(`CREATE SEQUENCE IF NOT EXISTS ${sequenceName}`);
      this.query(`ALTER TABLE ${tableName} ALTER COLUMN id SET DEFAULT nextval('${sequenceName}')`);
      this.query(`ALTER SEQUENCE ${sequenceName} OWNED BY ${tableName}.id`);
      this.query(`SELECT setval('${sequenceName}', COALESCE((SELECT MAX(id) FROM ${tableName}), 0) + 1, false)`);
    }
  }

  close() {
    waitFor(done => this.client.end(done));
  }
}

module.exports = PostgresDatabase;
module.exports.translateSql = translateSql;
